Updated contributor's guidelines
Be-Secure/BeSman pull request #150
Opened 2024-04-29 10:37 UTC by asa1997

2024-04-29 15:57 UTC, harimohanr commented on CONTRIBUTING.md
> +If you think you have found a security vulnerability in Spring Boot please DO NOT disclose it publicly until we’ve had a chance to fix it. Please don’t report security vulnerabilities using GitHub is
@asa1997 The project name is mentioned as Spring Boot. Correct this. Also, how does the contributor reach out to the maintainers in case of security vulnerability. Please provide your email id.

2024-04-29 15:59 UTC, harimohanr commented on CONTRIBUTING.md
> +    - The `dev` branch serves as the integration branch for ongoing development work.
@asa1997 Change the branch name to "develop" instead of "dev"

2024-04-29 16:02 UTC, harimohanr requested changes
@asa1997 Please address the review comments

2024-04-29 16:32 UTC, asa1997 commented
@harimohanr please review

2024-04-30 09:38 UTC, harimohanr commented on CONTRIBUTING.md
> +# Proposing a hange
@asa1997 Typo..

2024-04-30 09:48 UTC, harimohanr approved these changes
@asa1997 looks okay to me

2024-04-30 09:50 UTC, merged