Fixed typos and messages
Be-Secure/BeSman pull request #187
Opened 2024-06-10 12:19 UTC by anilsingla

Fixed typos and messages in attestation

2024-06-10 12:30 UTC, asa1997 requested changes

2024-06-10 12:30 UTC, asa1997 commented on src/main/bash/commands/besman-attest.sh
> +        which cosign 2>&1>/dev/null
Use this instead,
```code
if [[ -z $(which cosing) ]];
then
   if code
else
   else code
fi
```
or

```code
if [[ -z $(command -v cosing) ]];
then
   if code
else
   else code
fi
```

2024-06-10 12:30 UTC, asa1997 commented on src/main/bash/commands/besman-verify.sh
> +	which cosign 2>&1>/dev/null
Use this instead,
```code
if [[ -z $(which cosing) ]];
then
   if code
else
   else code
fi
```
or

```code
if [[ -z $(command -v cosing) ]];
then
   if code
else
   else code
fi
```

2024-06-10 12:30 UTC, asa1997 commented on src/main/bash/commands/besman-verify.sh
> +        cosign verify-blob $filename --key cosign.pub --bundle $filename.bundle 2>&1 | tee sigresult > /dev/null
Remove the hardcoding of sigresult. Use a variable with absolute path

2024-06-10 12:30 UTC, asa1997 commented on src/main/bash/commands/besman-verify.sh
> +	if grep "Verified OK" sigresult 2>&1>/dev/null &&  grep "Verified OK" attestresult 2>&1>/dev/null ;then
Remove the hardcoding of attestresult. Use a variable with absolute path

2024-06-10 12:30 UTC, asa1997 commented on src/main/bash/commands/besman-attest.sh
> +          curl --silent -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign_${LATEST_VERSION}_amd64.deb" 2>&1>/dev/null
See if you can go for a besman wrapper function under utils.

2024-06-10 14:00 UTC, anilsingla commented on src/main/bash/commands/besman-attest.sh
> +          curl --silent -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign_${LATEST_VERSION}_amd64.deb" 2>&1>/dev/null
we need -O flag which is not present in wrapper functions so can not use the wrapper functions

2024-06-11 04:14 UTC, asa1997 approved these changes
@anilsingla LGTM

2024-06-11 04:14 UTC, merged