'besman-save.sh script added(untested version)
Be-Secure/BeSman pull request #24
Opened 2021-12-01 16:19 UTC by jobyko

2021-12-01 16:24 UTC, asa1997 requested changes
@jobyko please take out the format checks for cve and assessment.

2021-12-02 11:55 UTC, jobyko commented
@asa1997 
Updated and added tested scripts.

2021-12-03 07:50 UTC, asa1997 requested changes
@jobyko  Please make the git commands as wrapper functions.

2021-12-06 02:49 UTC, jobyko commented
@asa1997 
Added script for bes publish. 

@sumodgeorge

2021-12-06 09:01 UTC, asa1997 commented on src/main/bash/besman-publish.sh
> +         gh pr  create --title "[Publish] Playbook name: $filename"
Please use __besman_xxxx wrapper functions for gh/git operations.

2021-12-06 09:01 UTC, asa1997 requested changes
@jobyko Please addresss the comments.

2021-12-13 03:01 UTC, jobyko commented
@asa1997 
Updated the besman-save with wrapper function.  

[Note]
Wrapper function updated in the besman-env-helper.sh, 
Name: function __besman_playbook_push

@sumodgeorge

2021-12-13 05:00 UTC, asa1997 commented on src/main/bash/besman-env-helpers.sh
> +function __besman_playbook_push
It would be better if it can be renamed as __besman_git_push/__besman_gh_push.

2021-12-13 05:04 UTC, asa1997 commented on src/main/bash/besman-publish.sh
> +         gh pr  create --title "[Publish] Playbook name: $filename"
@jobyko Please check this file

2021-12-13 05:05 UTC, asa1997 requested changes
@jobyko Please address the comments

2021-12-13 08:58 UTC, jobyko commented on src/main/bash/besman-env-helpers.sh
> +function __besman_playbook_push
Renamed the function

2022-01-06 10:15 UTC, closed without merging