Updated besman with 'bes modify' command
Be-Secure/BeSman pull request #32
Opened 2022-01-13 06:23 UTC by jobyko

@asa1997 
Please share your feedback 

@sumodgeorge

2022-01-13 07:25 UTC, asa1997 commented on src/main/bash/besman-mod.sh
> +function __besman_validate_playbook_type
This function is unnecessary

2022-01-13 07:26 UTC, asa1997 commented on src/main/bash/besman-mod.sh
> +         __besman_vim_playbook $filename || return 1
Please use jupyter notebook or vscode

2022-01-13 07:27 UTC, asa1997 requested changes
@jobyko Please address the comments

2022-01-18 10:30 UTC, jobyko commented
Added the requested modification

2022-01-19 05:22 UTC, closed without merging