BeSman updated with new 'bes modify' command
Be-Secure/BeSman pull request #35
Opened 2022-01-19 05:26 UTC by jobyko

@asa1997 
Please share your comments.

2022-01-19 05:29 UTC, asa1997 commented on src/main/bash/besman-modify.sh
> +function __bes_mod
Since command is modify this function name should be __bes_modify

2022-01-19 05:30 UTC, asa1997 commented on src/main/bash/besman-modify.sh
> +         __besman_git_stage $filename || return 1
I dont think these steps are necessary here. All these are handled by save command.

2022-01-19 05:30 UTC, asa1997 commented on src/main/bash/besman-modify.sh
> +         __besman_git_stage $filename || return 1
Modify should only help the user to modify the playbook he wishes.

2022-01-19 05:31 UTC, asa1997 requested changes
@jobyko Please address the comments.

2022-01-19 05:36 UTC, jobyko commented on src/main/bash/besman-modify.sh
> +         __besman_git_stage $filename || return 1
@asa1997 
Should we consider keeping, __besman_open_file to open file for edit.

2022-01-19 12:34 UTC, asa1997 approved these changes
@jobyko @panickervinod LGTM.

2022-01-20 05:31 UTC, panickervinod commented
@jobyko @asa1997 can this be called update rather than modify.?

2022-01-20 05:31 UTC, closed without merging

2022-01-20 05:32 UTC, panickervinod commented on src/main/bash/besman-modify.sh
> +function __bes_modify
@jobyko can this be renamed as __bes_modify to __bes_update ? do you see a name clash?