Updated BeSman with bes publish command
Be-Secure/BeSman pull request #36
Opened 2022-02-04 12:12 UTC by jobyko

2022-02-22 12:10 UTC, asa1997 commented on src/main/bash/besman-publish.sh
> +         __besman_gh_issue-pr $filename || return 1
Seperate the functions for issue and pr creation

2022-02-22 12:19 UTC, asa1997 commented on src/main/bash/besman-repo-helpers.sh
> +function __besman_gh_issue-pr
seperate the functions for pr and create

2022-02-22 12:20 UTC, asa1997 requested changes
@jobyko Please address the comments

2022-02-28 09:19 UTC, jobyko commented on src/main/bash/besman-publish.sh
> +         __besman_gh_issue-pr $filename || return 1
- [ ] spitted the function into two

2022-02-28 09:20 UTC, jobyko commented on src/main/bash/besman-repo-helpers.sh
> +function __besman_gh_issue-pr
completed

2022-02-28 09:31 UTC, closed without merging